# Generated by Django 4.2.4 on 2024-09-16 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConveyanceModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('da_code', models.CharField(max_length=100)),
                ('start_journey_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('end_journey_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_journey_date_time', models.DateTimeField()),
                ('end_journey_date_time', models.DateTimeField(blank=True, null=True)),
                ('transport_mode', models.TextField(blank=True, null=True)),
                ('transport_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('journey_status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conveyance',
                'verbose_name_plural': 'Conveyance',
                'db_table': 'rdl_conveyance',
            },
        ),
    ]
