# Generated by Django 4.2.4 on 2024-09-16 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conveyance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportModeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transport_name', models.CharField(max_length=255)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TransportMode',
                'verbose_name_plural': 'TransportMode',
                'db_table': 'rdl_transport_mode_list',
            },
        ),
    ]
