# Generated by Django 4.2.4 on 2024-09-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveyance_app', '0002_transportmodemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportmodemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
