# Generated by Django 4.2.4 on 2024-09-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveyance_app', '0003_alter_transportmodemodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conveyancemodel',
            name='end_journey_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='conveyancemodel',
            name='start_journey_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
