# Generated by Django 4.2.4 on 2024-09-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conveyance_app', '0004_conveyancemodel_end_journey_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conveyancemodel',
            name='end_journey_latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='conveyancemodel',
            name='end_journey_longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='conveyancemodel',
            name='start_journey_latitude',
            field=models.DecimalField(decimal_places=9, max_digits=9),
        ),
        migrations.AlterField(
            model_name='conveyancemodel',
            name='start_journey_longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=9, null=True),
        ),
    ]
