# Generated by Django 5.1.1 on 2024-09-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('billing_doc_no', models.CharField(max_length=10, unique=True)),
                ('partner', models.CharField(max_length=10)),
                ('da_code', models.CharField(max_length=10)),
                ('cash_collection', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('cash_collection_date_time', models.DateTimeField(blank=True, null=True)),
                ('cash_collection_latitude', models.DecimalField(decimal_places=16, max_digits=27, null=True)),
                ('cash_collection_longitude', models.DecimalField(decimal_places=16, max_digits=27, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
