# Generated by Django 5.1.1 on 2024-09-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0002_paymenthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'verbose_name': 'PaymentHistory', 'verbose_name_plural': 'PaymentHistory'},
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='route_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterModelTable(
            name='paymenthistory',
            table='rdl_payment_history',
        ),
    ]
