# Generated by Django 5.1.1 on 2024-09-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0003_alter_paymenthistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='billing_doc_no',
            field=models.CharField(max_length=10),
        ),
    ]
