# Generated by Django 5.1.1 on 2024-10-03 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0004_alter_paymenthistory_billing_doc_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('billing_doc_no', models.CharField(max_length=10, unique=True)),
                ('billing_date', models.DateField()),
                ('partner', models.CharField(max_length=10)),
                ('gate_pass_no', models.CharField(max_length=10)),
                ('da_code', models.CharField(max_length=8)),
                ('route_code', models.CharField(max_length=6, null=True)),
                ('return_date_time', models.DateTimeField(blank=True, null=True)),
                ('return_latitude', models.DecimalField(decimal_places=16, max_digits=27, null=True)),
                ('return_longitude', models.DecimalField(decimal_places=16, max_digits=27, null=True)),
                ('return_status', models.CharField(choices=[(0, 'NO'), (1, 'YES')], default=0, max_length=20, null=True)),
                ('return_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Return',
                'verbose_name_plural': 'Return',
                'db_table': 'rdl_return',
            },
        ),
        migrations.CreateModel(
            name='ReturnListModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matnr', models.CharField(max_length=40)),
                ('batch', models.CharField(max_length=40)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tp', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('net_val', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('return_quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('return_net_val', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection_app.returnmodel')),
            ],
            options={
                'verbose_name': 'Return List',
                'verbose_name_plural': 'Return List',
                'db_table': 'rdl_return_list',
            },
        ),
    ]
