# Generated by Django 5.1.1 on 2024-10-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0005_returnmodel_returnlistmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnlistmodel',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='returnlistmodel',
            name='net_val',
        ),
        migrations.RemoveField(
            model_name='returnlistmodel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='returnlistmodel',
            name='tp',
        ),
        migrations.RemoveField(
            model_name='returnlistmodel',
            name='vat',
        ),
        migrations.AddField(
            model_name='returnlistmodel',
            name='billing_date',
            field=models.DateField(default='2024-10-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnlistmodel',
            name='billing_doc_no',
            field=models.CharField(default='7869878', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnlistmodel',
            name='da_code',
            field=models.CharField(default='34353', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnlistmodel',
            name='gate_pass_no',
            field=models.CharField(default='9743798437', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnlistmodel',
            name='partner',
            field=models.CharField(default='87497', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnlistmodel',
            name='route_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
