# Generated by Django 5.1.1 on 2024-10-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0006_remove_returnlistmodel_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnlistmodel',
            name='billing_doc_no',
            field=models.CharField(max_length=10),
        ),
    ]
