# Generated by Django 5.1.1 on 2024-10-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0007_alter_returnlistmodel_billing_doc_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnlistmodel',
            name='return_time',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Cash_Collection', 'Cash_Collection')], max_length=20, null=True),
        ),
    ]
