# Generated by Django 4.2.4 on 2024-09-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_location_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlocationmodel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='customerlocationmodel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=27, null=True),
        ),
    ]
