# Generated by Django 4.2 on 2023-04-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_userlist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Delivery Assistant', 'Delivery Assistant'), ('Driver', 'Driver')], max_length=20, null=True),
        ),
    ]
