# Generated by Django 4.2.4 on 2024-09-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_adminuserlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='id',
            field=models.IntegerField(default=0),
        ),
    ]
