# Generated by Django 4.2 on 2023-06-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInfoModel',
            fields=[
                ('billing_doc_no', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('billing_date', models.TextField(blank=True)),
                ('delv_no', models.TextField(blank=True)),
                ('route', models.TextField(blank=True)),
                ('vehicle_no', models.TextField(blank=True)),
                ('da_code', models.TextField(blank=True)),
                ('da_name', models.TextField(blank=True)),
                ('route_name', models.TextField(blank=True)),
                ('billing_type', models.TextField(blank=True)),
                ('partner', models.TextField(blank=True)),
                ('matnr', models.TextField(blank=True)),
                ('quantity', models.TextField(blank=True)),
                ('tp', models.TextField(blank=True)),
                ('vat', models.TextField(blank=True)),
                ('net_val', models.TextField(blank=True)),
                ('assigment', models.TextField(blank=True)),
                ('gate_pass_no', models.TextField(blank=True)),
                ('batch', models.TextField(blank=True)),
                ('plant', models.TextField(blank=True)),
                ('team', models.TextField(blank=True)),
                ('created_on', models.TextField(blank=True)),
                ('material_name', models.TextField(blank=True)),
                ('brand_description', models.TextField(blank=True)),
                ('brand_name', models.TextField(blank=True)),
                ('customer_name', models.TextField(blank=True)),
                ('customer_address', models.TextField(blank=True)),
                ('customer_mobile', models.TextField(blank=True)),
                ('latitude', models.TextField(blank=True)),
                ('longitude', models.TextField(blank=True)),
                ('received_quantity', models.TextField(blank=True)),
                ('delivery_status', models.TextField(blank=True)),
                ('cash_collection', models.TextField(blank=True)),
                ('collection_status', models.TextField(blank=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('billing_doc_no', models.CharField(max_length=10, unique=True)),
                ('billing_date', models.DateField()),
                ('partner', models.CharField(max_length=10)),
                ('gate_pass_no', models.CharField(max_length=10)),
                ('da_code', models.CharField(max_length=8)),
                ('vehicle_no', models.CharField(max_length=25, null=True)),
                ('route_code', models.CharField(max_length=6, null=True)),
                ('delivery_date_time', models.DateTimeField(blank=True, null=True)),
                ('cash_collection_date_time', models.DateTimeField(blank=True, null=True)),
                ('return_date_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_latitude', models.DecimalField(decimal_places=16, max_digits=27, null=True)),
                ('delivery_longitude', models.DecimalField(decimal_places=16, max_digits=27, null=True)),
                ('cash_collection_latitude', models.DecimalField(decimal_places=16, max_digits=27, null=True)),
                ('cash_collection_longitude', models.DecimalField(decimal_places=16, max_digits=27, null=True)),
                ('return_latitude', models.DecimalField(decimal_places=16, max_digits=27, null=True)),
                ('return_longitude', models.DecimalField(decimal_places=16, max_digits=27, null=True)),
                ('transport_type', models.CharField(choices=[('Car', 'Car'), ('Walk', 'Walk'), ('Rickshaw', 'Rickshaw')], max_length=20, null=True)),
                ('delivery_status', models.CharField(choices=[('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Done', 'Done')], max_length=20, null=True)),
                ('cash_collection', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('cash_collection_status', models.CharField(choices=[('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Done', 'Done')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('last_status', models.CharField(max_length=80, null=True)),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Delivery',
                'db_table': 'rdl_delivery',
            },
        ),
        migrations.CreateModel(
            name='DeliveryListModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matnr', models.CharField(max_length=40)),
                ('batch', models.CharField(max_length=10, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('tp', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('net_val', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('delivery_quantity', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('delivery_net_val', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('return_quantity', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('return_net_val', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverys', to='delivery_app.deliverymodel')),
            ],
            options={
                'verbose_name': 'Delivery List',
                'verbose_name_plural': 'Delivery List',
                'db_table': 'rdl_delivery_list',
            },
        ),
    ]
