# Generated by Django 5.1.1 on 2024-09-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0002_deliverymodel_due_amount_deliverymodel_net_val_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymodel',
            name='return_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
    ]
