# Generated by Django 5.1.1 on 2024-09-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0003_deliverymodel_return_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymodel',
            name='return_status',
            field=models.CharField(choices=[(0, 'NO'), (1, 'YES')], default=0, max_length=20, null=True),
        ),
    ]
