# Generated by Django 5.1.1 on 2024-10-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('da_code', models.CharField(max_length=10)),
                ('route_code', models.CharField(max_length=10, null=True)),
                ('partner', models.CharField(max_length=10)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('visit_time', models.TimeField(auto_now_add=True)),
                ('visit_type', models.CharField(choices=[('Customer_Unavailable', 'Customer_Unavailable'), ('Customer_Busy', 'Customer_Busy'), ('Insufficient_Amount', 'Insufficient_Amount')], max_length=50)),
                ('comment', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
