# Generated by Django 5.1.1 on 2024-10-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visithistorymodel',
            options={'verbose_name': 'VisitHistory', 'verbose_name_plural': 'VisitHistory'},
        ),
        migrations.RemoveField(
            model_name='visithistorymodel',
            name='visit_date',
        ),
        migrations.RemoveField(
            model_name='visithistorymodel',
            name='visit_time',
        ),
        migrations.AddField(
            model_name='visithistorymodel',
            name='visit_latitude',
            field=models.DecimalField(decimal_places=16, max_digits=27, null=True),
        ),
        migrations.AddField(
            model_name='visithistorymodel',
            name='visit_longitude',
            field=models.DecimalField(decimal_places=16, max_digits=27, null=True),
        ),
        migrations.AlterModelTable(
            name='visithistorymodel',
            table='rdl_visit_history',
        ),
    ]
